package com.industry.platform.dto.generator;

import java.util.Date;

public class IndbProductDetail {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column indb_product_detail.id
     *
     * @mbggenerated Sun Dec 08 20:53:52 CST 2019
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column indb_product_detail.name
     *
     * @mbggenerated Sun Dec 08 20:53:52 CST 2019
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column indb_product_detail.description
     *
     * @mbggenerated Sun Dec 08 20:53:52 CST 2019
     */
    private String description;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column indb_product_detail.pic
     *
     * @mbggenerated Sun Dec 08 20:53:52 CST 2019
     */
    private String pic;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column indb_product_detail.sort
     *
     * @mbggenerated Sun Dec 08 20:53:52 CST 2019
     */
    private Integer sort;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column indb_product_detail.top
     *
     * @mbggenerated Sun Dec 08 20:53:52 CST 2019
     */
    private Integer top;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column indb_product_detail.tag_id
     *
     * @mbggenerated Sun Dec 08 20:53:52 CST 2019
     */
    private Integer tagId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column indb_product_detail.is_deleted
     *
     * @mbggenerated Sun Dec 08 20:53:52 CST 2019
     */
    private Integer isDeleted;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column indb_product_detail.create_user
     *
     * @mbggenerated Sun Dec 08 20:53:52 CST 2019
     */
    private Integer createUser;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column indb_product_detail.create_date
     *
     * @mbggenerated Sun Dec 08 20:53:52 CST 2019
     */
    private Date createDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column indb_product_detail.update_user
     *
     * @mbggenerated Sun Dec 08 20:53:52 CST 2019
     */
    private Integer updateUser;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column indb_product_detail.update_date
     *
     * @mbggenerated Sun Dec 08 20:53:52 CST 2019
     */
    private Date updateDate;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column indb_product_detail.id
     *
     * @return the value of indb_product_detail.id
     *
     * @mbggenerated Sun Dec 08 20:53:52 CST 2019
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column indb_product_detail.id
     *
     * @param id the value for indb_product_detail.id
     *
     * @mbggenerated Sun Dec 08 20:53:52 CST 2019
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column indb_product_detail.name
     *
     * @return the value of indb_product_detail.name
     *
     * @mbggenerated Sun Dec 08 20:53:52 CST 2019
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column indb_product_detail.name
     *
     * @param name the value for indb_product_detail.name
     *
     * @mbggenerated Sun Dec 08 20:53:52 CST 2019
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column indb_product_detail.description
     *
     * @return the value of indb_product_detail.description
     *
     * @mbggenerated Sun Dec 08 20:53:52 CST 2019
     */
    public String getDescription() {
        return description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column indb_product_detail.description
     *
     * @param description the value for indb_product_detail.description
     *
     * @mbggenerated Sun Dec 08 20:53:52 CST 2019
     */
    public void setDescription(String description) {
        this.description = description == null ? null : description.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column indb_product_detail.pic
     *
     * @return the value of indb_product_detail.pic
     *
     * @mbggenerated Sun Dec 08 20:53:52 CST 2019
     */
    public String getPic() {
        return pic;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column indb_product_detail.pic
     *
     * @param pic the value for indb_product_detail.pic
     *
     * @mbggenerated Sun Dec 08 20:53:52 CST 2019
     */
    public void setPic(String pic) {
        this.pic = pic == null ? null : pic.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column indb_product_detail.sort
     *
     * @return the value of indb_product_detail.sort
     *
     * @mbggenerated Sun Dec 08 20:53:52 CST 2019
     */
    public Integer getSort() {
        return sort;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column indb_product_detail.sort
     *
     * @param sort the value for indb_product_detail.sort
     *
     * @mbggenerated Sun Dec 08 20:53:52 CST 2019
     */
    public void setSort(Integer sort) {
        this.sort = sort;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column indb_product_detail.top
     *
     * @return the value of indb_product_detail.top
     *
     * @mbggenerated Sun Dec 08 20:53:52 CST 2019
     */
    public Integer getTop() {
        return top;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column indb_product_detail.top
     *
     * @param top the value for indb_product_detail.top
     *
     * @mbggenerated Sun Dec 08 20:53:52 CST 2019
     */
    public void setTop(Integer top) {
        this.top = top;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column indb_product_detail.tag_id
     *
     * @return the value of indb_product_detail.tag_id
     *
     * @mbggenerated Sun Dec 08 20:53:52 CST 2019
     */
    public Integer getTagId() {
        return tagId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column indb_product_detail.tag_id
     *
     * @param tagId the value for indb_product_detail.tag_id
     *
     * @mbggenerated Sun Dec 08 20:53:52 CST 2019
     */
    public void setTagId(Integer tagId) {
        this.tagId = tagId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column indb_product_detail.is_deleted
     *
     * @return the value of indb_product_detail.is_deleted
     *
     * @mbggenerated Sun Dec 08 20:53:52 CST 2019
     */
    public Integer getIsDeleted() {
        return isDeleted;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column indb_product_detail.is_deleted
     *
     * @param isDeleted the value for indb_product_detail.is_deleted
     *
     * @mbggenerated Sun Dec 08 20:53:52 CST 2019
     */
    public void setIsDeleted(Integer isDeleted) {
        this.isDeleted = isDeleted;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column indb_product_detail.create_user
     *
     * @return the value of indb_product_detail.create_user
     *
     * @mbggenerated Sun Dec 08 20:53:52 CST 2019
     */
    public Integer getCreateUser() {
        return createUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column indb_product_detail.create_user
     *
     * @param createUser the value for indb_product_detail.create_user
     *
     * @mbggenerated Sun Dec 08 20:53:52 CST 2019
     */
    public void setCreateUser(Integer createUser) {
        this.createUser = createUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column indb_product_detail.create_date
     *
     * @return the value of indb_product_detail.create_date
     *
     * @mbggenerated Sun Dec 08 20:53:52 CST 2019
     */
    public Date getCreateDate() {
        return createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column indb_product_detail.create_date
     *
     * @param createDate the value for indb_product_detail.create_date
     *
     * @mbggenerated Sun Dec 08 20:53:52 CST 2019
     */
    public void setCreateDate(Date createDate) {
        this.createDate = createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column indb_product_detail.update_user
     *
     * @return the value of indb_product_detail.update_user
     *
     * @mbggenerated Sun Dec 08 20:53:52 CST 2019
     */
    public Integer getUpdateUser() {
        return updateUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column indb_product_detail.update_user
     *
     * @param updateUser the value for indb_product_detail.update_user
     *
     * @mbggenerated Sun Dec 08 20:53:52 CST 2019
     */
    public void setUpdateUser(Integer updateUser) {
        this.updateUser = updateUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column indb_product_detail.update_date
     *
     * @return the value of indb_product_detail.update_date
     *
     * @mbggenerated Sun Dec 08 20:53:52 CST 2019
     */
    public Date getUpdateDate() {
        return updateDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column indb_product_detail.update_date
     *
     * @param updateDate the value for indb_product_detail.update_date
     *
     * @mbggenerated Sun Dec 08 20:53:52 CST 2019
     */
    public void setUpdateDate(Date updateDate) {
        this.updateDate = updateDate;
    }
}