package com.industry.platform.dto.generator;

import java.util.Date;

public class IndbProductDetail {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column indb_product_detail.id
     *
     * @mbggenerated Tue Feb 18 21:34:23 CST 2020
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column indb_product_detail.name
     *
     * @mbggenerated Tue Feb 18 21:34:23 CST 2020
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column indb_product_detail.description
     *
     * @mbggenerated Tue Feb 18 21:34:23 CST 2020
     */
    private String description;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column indb_product_detail.pic
     *
     * @mbggenerated Tue Feb 18 21:34:23 CST 2020
     */
    private String pic;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column indb_product_detail.sort
     *
     * @mbggenerated Tue Feb 18 21:34:23 CST 2020
     */
    private Integer sort;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column indb_product_detail.is_top
     *
     * @mbggenerated Tue Feb 18 21:34:23 CST 2020
     */
    private Integer isTop;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column indb_product_detail.tag_id
     *
     * @mbggenerated Tue Feb 18 21:34:23 CST 2020
     */
    private Integer tagId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column indb_product_detail.is_used
     *
     * @mbggenerated Tue Feb 18 21:34:23 CST 2020
     */
    private Integer isUsed;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column indb_product_detail.create_by
     *
     * @mbggenerated Tue Feb 18 21:34:23 CST 2020
     */
    private String createBy;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column indb_product_detail.create_time
     *
     * @mbggenerated Tue Feb 18 21:34:23 CST 2020
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column indb_product_detail.update_by
     *
     * @mbggenerated Tue Feb 18 21:34:23 CST 2020
     */
    private String updateBy;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column indb_product_detail.update_time
     *
     * @mbggenerated Tue Feb 18 21:34:23 CST 2020
     */
    private Date updateTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column indb_product_detail.id
     *
     * @return the value of indb_product_detail.id
     *
     * @mbggenerated Tue Feb 18 21:34:23 CST 2020
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column indb_product_detail.id
     *
     * @param id the value for indb_product_detail.id
     *
     * @mbggenerated Tue Feb 18 21:34:23 CST 2020
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column indb_product_detail.name
     *
     * @return the value of indb_product_detail.name
     *
     * @mbggenerated Tue Feb 18 21:34:23 CST 2020
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column indb_product_detail.name
     *
     * @param name the value for indb_product_detail.name
     *
     * @mbggenerated Tue Feb 18 21:34:23 CST 2020
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column indb_product_detail.description
     *
     * @return the value of indb_product_detail.description
     *
     * @mbggenerated Tue Feb 18 21:34:23 CST 2020
     */
    public String getDescription() {
        return description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column indb_product_detail.description
     *
     * @param description the value for indb_product_detail.description
     *
     * @mbggenerated Tue Feb 18 21:34:23 CST 2020
     */
    public void setDescription(String description) {
        this.description = description == null ? null : description.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column indb_product_detail.pic
     *
     * @return the value of indb_product_detail.pic
     *
     * @mbggenerated Tue Feb 18 21:34:23 CST 2020
     */
    public String getPic() {
        return pic;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column indb_product_detail.pic
     *
     * @param pic the value for indb_product_detail.pic
     *
     * @mbggenerated Tue Feb 18 21:34:23 CST 2020
     */
    public void setPic(String pic) {
        this.pic = pic == null ? null : pic.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column indb_product_detail.sort
     *
     * @return the value of indb_product_detail.sort
     *
     * @mbggenerated Tue Feb 18 21:34:23 CST 2020
     */
    public Integer getSort() {
        return sort;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column indb_product_detail.sort
     *
     * @param sort the value for indb_product_detail.sort
     *
     * @mbggenerated Tue Feb 18 21:34:23 CST 2020
     */
    public void setSort(Integer sort) {
        this.sort = sort;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column indb_product_detail.is_top
     *
     * @return the value of indb_product_detail.is_top
     *
     * @mbggenerated Tue Feb 18 21:34:23 CST 2020
     */
    public Integer getIsTop() {
        return isTop;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column indb_product_detail.is_top
     *
     * @param isTop the value for indb_product_detail.is_top
     *
     * @mbggenerated Tue Feb 18 21:34:23 CST 2020
     */
    public void setIsTop(Integer isTop) {
        this.isTop = isTop;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column indb_product_detail.tag_id
     *
     * @return the value of indb_product_detail.tag_id
     *
     * @mbggenerated Tue Feb 18 21:34:23 CST 2020
     */
    public Integer getTagId() {
        return tagId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column indb_product_detail.tag_id
     *
     * @param tagId the value for indb_product_detail.tag_id
     *
     * @mbggenerated Tue Feb 18 21:34:23 CST 2020
     */
    public void setTagId(Integer tagId) {
        this.tagId = tagId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column indb_product_detail.is_used
     *
     * @return the value of indb_product_detail.is_used
     *
     * @mbggenerated Tue Feb 18 21:34:23 CST 2020
     */
    public Integer getIsUsed() {
        return isUsed;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column indb_product_detail.is_used
     *
     * @param isUsed the value for indb_product_detail.is_used
     *
     * @mbggenerated Tue Feb 18 21:34:23 CST 2020
     */
    public void setIsUsed(Integer isUsed) {
        this.isUsed = isUsed;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column indb_product_detail.create_by
     *
     * @return the value of indb_product_detail.create_by
     *
     * @mbggenerated Tue Feb 18 21:34:23 CST 2020
     */
    public String getCreateBy() {
        return createBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column indb_product_detail.create_by
     *
     * @param createBy the value for indb_product_detail.create_by
     *
     * @mbggenerated Tue Feb 18 21:34:23 CST 2020
     */
    public void setCreateBy(String createBy) {
        this.createBy = createBy == null ? null : createBy.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column indb_product_detail.create_time
     *
     * @return the value of indb_product_detail.create_time
     *
     * @mbggenerated Tue Feb 18 21:34:23 CST 2020
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column indb_product_detail.create_time
     *
     * @param createTime the value for indb_product_detail.create_time
     *
     * @mbggenerated Tue Feb 18 21:34:23 CST 2020
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column indb_product_detail.update_by
     *
     * @return the value of indb_product_detail.update_by
     *
     * @mbggenerated Tue Feb 18 21:34:23 CST 2020
     */
    public String getUpdateBy() {
        return updateBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column indb_product_detail.update_by
     *
     * @param updateBy the value for indb_product_detail.update_by
     *
     * @mbggenerated Tue Feb 18 21:34:23 CST 2020
     */
    public void setUpdateBy(String updateBy) {
        this.updateBy = updateBy == null ? null : updateBy.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column indb_product_detail.update_time
     *
     * @return the value of indb_product_detail.update_time
     *
     * @mbggenerated Tue Feb 18 21:34:23 CST 2020
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column indb_product_detail.update_time
     *
     * @param updateTime the value for indb_product_detail.update_time
     *
     * @mbggenerated Tue Feb 18 21:34:23 CST 2020
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }
}