package com.industry.platform.dto.generator;

import java.util.Date;

public class IndbContract {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column indb_contract.id
     *
     * @mbggenerated Sun Dec 08 20:53:52 CST 2019
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column indb_contract.name
     *
     * @mbggenerated Sun Dec 08 20:53:52 CST 2019
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column indb_contract.email
     *
     * @mbggenerated Sun Dec 08 20:53:52 CST 2019
     */
    private String email;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column indb_contract.phone
     *
     * @mbggenerated Sun Dec 08 20:53:52 CST 2019
     */
    private Integer phone;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column indb_contract.is_reply
     *
     * @mbggenerated Sun Dec 08 20:53:52 CST 2019
     */
    private Integer isReply;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column indb_contract.create_user
     *
     * @mbggenerated Sun Dec 08 20:53:52 CST 2019
     */
    private Integer createUser;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column indb_contract.create_date
     *
     * @mbggenerated Sun Dec 08 20:53:52 CST 2019
     */
    private Date createDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column indb_contract.update_user
     *
     * @mbggenerated Sun Dec 08 20:53:52 CST 2019
     */
    private Integer updateUser;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column indb_contract.update_date
     *
     * @mbggenerated Sun Dec 08 20:53:52 CST 2019
     */
    private Date updateDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column indb_contract.content
     *
     * @mbggenerated Sun Dec 08 20:53:52 CST 2019
     */
    private String content;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column indb_contract.id
     *
     * @return the value of indb_contract.id
     *
     * @mbggenerated Sun Dec 08 20:53:52 CST 2019
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column indb_contract.id
     *
     * @param id the value for indb_contract.id
     *
     * @mbggenerated Sun Dec 08 20:53:52 CST 2019
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column indb_contract.name
     *
     * @return the value of indb_contract.name
     *
     * @mbggenerated Sun Dec 08 20:53:52 CST 2019
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column indb_contract.name
     *
     * @param name the value for indb_contract.name
     *
     * @mbggenerated Sun Dec 08 20:53:52 CST 2019
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column indb_contract.email
     *
     * @return the value of indb_contract.email
     *
     * @mbggenerated Sun Dec 08 20:53:52 CST 2019
     */
    public String getEmail() {
        return email;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column indb_contract.email
     *
     * @param email the value for indb_contract.email
     *
     * @mbggenerated Sun Dec 08 20:53:52 CST 2019
     */
    public void setEmail(String email) {
        this.email = email == null ? null : email.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column indb_contract.phone
     *
     * @return the value of indb_contract.phone
     *
     * @mbggenerated Sun Dec 08 20:53:52 CST 2019
     */
    public Integer getPhone() {
        return phone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column indb_contract.phone
     *
     * @param phone the value for indb_contract.phone
     *
     * @mbggenerated Sun Dec 08 20:53:52 CST 2019
     */
    public void setPhone(Integer phone) {
        this.phone = phone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column indb_contract.is_reply
     *
     * @return the value of indb_contract.is_reply
     *
     * @mbggenerated Sun Dec 08 20:53:52 CST 2019
     */
    public Integer getIsReply() {
        return isReply;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column indb_contract.is_reply
     *
     * @param isReply the value for indb_contract.is_reply
     *
     * @mbggenerated Sun Dec 08 20:53:52 CST 2019
     */
    public void setIsReply(Integer isReply) {
        this.isReply = isReply;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column indb_contract.create_user
     *
     * @return the value of indb_contract.create_user
     *
     * @mbggenerated Sun Dec 08 20:53:52 CST 2019
     */
    public Integer getCreateUser() {
        return createUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column indb_contract.create_user
     *
     * @param createUser the value for indb_contract.create_user
     *
     * @mbggenerated Sun Dec 08 20:53:52 CST 2019
     */
    public void setCreateUser(Integer createUser) {
        this.createUser = createUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column indb_contract.create_date
     *
     * @return the value of indb_contract.create_date
     *
     * @mbggenerated Sun Dec 08 20:53:52 CST 2019
     */
    public Date getCreateDate() {
        return createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column indb_contract.create_date
     *
     * @param createDate the value for indb_contract.create_date
     *
     * @mbggenerated Sun Dec 08 20:53:52 CST 2019
     */
    public void setCreateDate(Date createDate) {
        this.createDate = createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column indb_contract.update_user
     *
     * @return the value of indb_contract.update_user
     *
     * @mbggenerated Sun Dec 08 20:53:52 CST 2019
     */
    public Integer getUpdateUser() {
        return updateUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column indb_contract.update_user
     *
     * @param updateUser the value for indb_contract.update_user
     *
     * @mbggenerated Sun Dec 08 20:53:52 CST 2019
     */
    public void setUpdateUser(Integer updateUser) {
        this.updateUser = updateUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column indb_contract.update_date
     *
     * @return the value of indb_contract.update_date
     *
     * @mbggenerated Sun Dec 08 20:53:52 CST 2019
     */
    public Date getUpdateDate() {
        return updateDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column indb_contract.update_date
     *
     * @param updateDate the value for indb_contract.update_date
     *
     * @mbggenerated Sun Dec 08 20:53:52 CST 2019
     */
    public void setUpdateDate(Date updateDate) {
        this.updateDate = updateDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column indb_contract.content
     *
     * @return the value of indb_contract.content
     *
     * @mbggenerated Sun Dec 08 20:53:52 CST 2019
     */
    public String getContent() {
        return content;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column indb_contract.content
     *
     * @param content the value for indb_contract.content
     *
     * @mbggenerated Sun Dec 08 20:53:52 CST 2019
     */
    public void setContent(String content) {
        this.content = content == null ? null : content.trim();
    }
}