package com.industry.platform.dto.generator;

import java.util.Date;

public class IndbProductTag {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column indb_product_tag.id
     *
     * @mbggenerated Sun Dec 08 20:53:52 CST 2019
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column indb_product_tag.name
     *
     * @mbggenerated Sun Dec 08 20:53:52 CST 2019
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column indb_product_tag.parent_id
     *
     * @mbggenerated Sun Dec 08 20:53:52 CST 2019
     */
    private Integer parentId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column indb_product_tag.sort
     *
     * @mbggenerated Sun Dec 08 20:53:52 CST 2019
     */
    private Integer sort;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column indb_product_tag.is_deleted
     *
     * @mbggenerated Sun Dec 08 20:53:52 CST 2019
     */
    private Integer isDeleted;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column indb_product_tag.create_user
     *
     * @mbggenerated Sun Dec 08 20:53:52 CST 2019
     */
    private Integer createUser;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column indb_product_tag.create_date
     *
     * @mbggenerated Sun Dec 08 20:53:52 CST 2019
     */
    private Date createDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column indb_product_tag.update_user
     *
     * @mbggenerated Sun Dec 08 20:53:52 CST 2019
     */
    private Integer updateUser;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column indb_product_tag.update_date
     *
     * @mbggenerated Sun Dec 08 20:53:52 CST 2019
     */
    private Date updateDate;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column indb_product_tag.id
     *
     * @return the value of indb_product_tag.id
     *
     * @mbggenerated Sun Dec 08 20:53:52 CST 2019
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column indb_product_tag.id
     *
     * @param id the value for indb_product_tag.id
     *
     * @mbggenerated Sun Dec 08 20:53:52 CST 2019
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column indb_product_tag.name
     *
     * @return the value of indb_product_tag.name
     *
     * @mbggenerated Sun Dec 08 20:53:52 CST 2019
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column indb_product_tag.name
     *
     * @param name the value for indb_product_tag.name
     *
     * @mbggenerated Sun Dec 08 20:53:52 CST 2019
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column indb_product_tag.parent_id
     *
     * @return the value of indb_product_tag.parent_id
     *
     * @mbggenerated Sun Dec 08 20:53:52 CST 2019
     */
    public Integer getParentId() {
        return parentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column indb_product_tag.parent_id
     *
     * @param parentId the value for indb_product_tag.parent_id
     *
     * @mbggenerated Sun Dec 08 20:53:52 CST 2019
     */
    public void setParentId(Integer parentId) {
        this.parentId = parentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column indb_product_tag.sort
     *
     * @return the value of indb_product_tag.sort
     *
     * @mbggenerated Sun Dec 08 20:53:52 CST 2019
     */
    public Integer getSort() {
        return sort;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column indb_product_tag.sort
     *
     * @param sort the value for indb_product_tag.sort
     *
     * @mbggenerated Sun Dec 08 20:53:52 CST 2019
     */
    public void setSort(Integer sort) {
        this.sort = sort;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column indb_product_tag.is_deleted
     *
     * @return the value of indb_product_tag.is_deleted
     *
     * @mbggenerated Sun Dec 08 20:53:52 CST 2019
     */
    public Integer getIsDeleted() {
        return isDeleted;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column indb_product_tag.is_deleted
     *
     * @param isDeleted the value for indb_product_tag.is_deleted
     *
     * @mbggenerated Sun Dec 08 20:53:52 CST 2019
     */
    public void setIsDeleted(Integer isDeleted) {
        this.isDeleted = isDeleted;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column indb_product_tag.create_user
     *
     * @return the value of indb_product_tag.create_user
     *
     * @mbggenerated Sun Dec 08 20:53:52 CST 2019
     */
    public Integer getCreateUser() {
        return createUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column indb_product_tag.create_user
     *
     * @param createUser the value for indb_product_tag.create_user
     *
     * @mbggenerated Sun Dec 08 20:53:52 CST 2019
     */
    public void setCreateUser(Integer createUser) {
        this.createUser = createUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column indb_product_tag.create_date
     *
     * @return the value of indb_product_tag.create_date
     *
     * @mbggenerated Sun Dec 08 20:53:52 CST 2019
     */
    public Date getCreateDate() {
        return createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column indb_product_tag.create_date
     *
     * @param createDate the value for indb_product_tag.create_date
     *
     * @mbggenerated Sun Dec 08 20:53:52 CST 2019
     */
    public void setCreateDate(Date createDate) {
        this.createDate = createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column indb_product_tag.update_user
     *
     * @return the value of indb_product_tag.update_user
     *
     * @mbggenerated Sun Dec 08 20:53:52 CST 2019
     */
    public Integer getUpdateUser() {
        return updateUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column indb_product_tag.update_user
     *
     * @param updateUser the value for indb_product_tag.update_user
     *
     * @mbggenerated Sun Dec 08 20:53:52 CST 2019
     */
    public void setUpdateUser(Integer updateUser) {
        this.updateUser = updateUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column indb_product_tag.update_date
     *
     * @return the value of indb_product_tag.update_date
     *
     * @mbggenerated Sun Dec 08 20:53:52 CST 2019
     */
    public Date getUpdateDate() {
        return updateDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column indb_product_tag.update_date
     *
     * @param updateDate the value for indb_product_tag.update_date
     *
     * @mbggenerated Sun Dec 08 20:53:52 CST 2019
     */
    public void setUpdateDate(Date updateDate) {
        this.updateDate = updateDate;
    }
}