package com.industry.platform.dto.generator;

import java.util.Date;

public class IndbAttachment {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column indb_attachment.id
     *
     * @mbggenerated Tue Feb 18 21:34:23 CST 2020
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column indb_attachment.name
     *
     * @mbggenerated Tue Feb 18 21:34:23 CST 2020
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column indb_attachment.type
     *
     * @mbggenerated Tue Feb 18 21:34:23 CST 2020
     */
    private String type;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column indb_attachment.address
     *
     * @mbggenerated Tue Feb 18 21:34:23 CST 2020
     */
    private String address;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column indb_attachment.create_by
     *
     * @mbggenerated Tue Feb 18 21:34:23 CST 2020
     */
    private String createBy;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column indb_attachment.create_time
     *
     * @mbggenerated Tue Feb 18 21:34:23 CST 2020
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column indb_attachment.update_by
     *
     * @mbggenerated Tue Feb 18 21:34:23 CST 2020
     */
    private String updateBy;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column indb_attachment.update_time
     *
     * @mbggenerated Tue Feb 18 21:34:23 CST 2020
     */
    private Date updateTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column indb_attachment.id
     *
     * @return the value of indb_attachment.id
     *
     * @mbggenerated Tue Feb 18 21:34:23 CST 2020
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column indb_attachment.id
     *
     * @param id the value for indb_attachment.id
     *
     * @mbggenerated Tue Feb 18 21:34:23 CST 2020
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column indb_attachment.name
     *
     * @return the value of indb_attachment.name
     *
     * @mbggenerated Tue Feb 18 21:34:23 CST 2020
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column indb_attachment.name
     *
     * @param name the value for indb_attachment.name
     *
     * @mbggenerated Tue Feb 18 21:34:23 CST 2020
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column indb_attachment.type
     *
     * @return the value of indb_attachment.type
     *
     * @mbggenerated Tue Feb 18 21:34:23 CST 2020
     */
    public String getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column indb_attachment.type
     *
     * @param type the value for indb_attachment.type
     *
     * @mbggenerated Tue Feb 18 21:34:23 CST 2020
     */
    public void setType(String type) {
        this.type = type == null ? null : type.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column indb_attachment.address
     *
     * @return the value of indb_attachment.address
     *
     * @mbggenerated Tue Feb 18 21:34:23 CST 2020
     */
    public String getAddress() {
        return address;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column indb_attachment.address
     *
     * @param address the value for indb_attachment.address
     *
     * @mbggenerated Tue Feb 18 21:34:23 CST 2020
     */
    public void setAddress(String address) {
        this.address = address == null ? null : address.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column indb_attachment.create_by
     *
     * @return the value of indb_attachment.create_by
     *
     * @mbggenerated Tue Feb 18 21:34:23 CST 2020
     */
    public String getCreateBy() {
        return createBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column indb_attachment.create_by
     *
     * @param createBy the value for indb_attachment.create_by
     *
     * @mbggenerated Tue Feb 18 21:34:23 CST 2020
     */
    public void setCreateBy(String createBy) {
        this.createBy = createBy == null ? null : createBy.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column indb_attachment.create_time
     *
     * @return the value of indb_attachment.create_time
     *
     * @mbggenerated Tue Feb 18 21:34:23 CST 2020
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column indb_attachment.create_time
     *
     * @param createTime the value for indb_attachment.create_time
     *
     * @mbggenerated Tue Feb 18 21:34:23 CST 2020
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column indb_attachment.update_by
     *
     * @return the value of indb_attachment.update_by
     *
     * @mbggenerated Tue Feb 18 21:34:23 CST 2020
     */
    public String getUpdateBy() {
        return updateBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column indb_attachment.update_by
     *
     * @param updateBy the value for indb_attachment.update_by
     *
     * @mbggenerated Tue Feb 18 21:34:23 CST 2020
     */
    public void setUpdateBy(String updateBy) {
        this.updateBy = updateBy == null ? null : updateBy.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column indb_attachment.update_time
     *
     * @return the value of indb_attachment.update_time
     *
     * @mbggenerated Tue Feb 18 21:34:23 CST 2020
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column indb_attachment.update_time
     *
     * @param updateTime the value for indb_attachment.update_time
     *
     * @mbggenerated Tue Feb 18 21:34:23 CST 2020
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }
}