package com.industry.platform.dto.generator;

import java.util.Date;

public class IndbProductTag {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column indb_product_tag.id
     *
     * @mbggenerated Tue Feb 18 21:34:23 CST 2020
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column indb_product_tag.name
     *
     * @mbggenerated Tue Feb 18 21:34:23 CST 2020
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column indb_product_tag.parent_id
     *
     * @mbggenerated Tue Feb 18 21:34:23 CST 2020
     */
    private Integer parentId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column indb_product_tag.sort
     *
     * @mbggenerated Tue Feb 18 21:34:23 CST 2020
     */
    private Integer sort;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column indb_product_tag.is_deleted
     *
     * @mbggenerated Tue Feb 18 21:34:23 CST 2020
     */
    private Integer isDeleted;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column indb_product_tag.create_by
     *
     * @mbggenerated Tue Feb 18 21:34:23 CST 2020
     */
    private Integer createBy;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column indb_product_tag.create_name
     *
     * @mbggenerated Tue Feb 18 21:34:23 CST 2020
     */
    private String createName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column indb_product_tag.create_time
     *
     * @mbggenerated Tue Feb 18 21:34:23 CST 2020
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column indb_product_tag.update_by
     *
     * @mbggenerated Tue Feb 18 21:34:23 CST 2020
     */
    private Integer updateBy;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column indb_product_tag.update_name
     *
     * @mbggenerated Tue Feb 18 21:34:23 CST 2020
     */
    private Date updateName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column indb_product_tag.update_time
     *
     * @mbggenerated Tue Feb 18 21:34:23 CST 2020
     */
    private Date updateTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column indb_product_tag.id
     *
     * @return the value of indb_product_tag.id
     *
     * @mbggenerated Tue Feb 18 21:34:23 CST 2020
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column indb_product_tag.id
     *
     * @param id the value for indb_product_tag.id
     *
     * @mbggenerated Tue Feb 18 21:34:23 CST 2020
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column indb_product_tag.name
     *
     * @return the value of indb_product_tag.name
     *
     * @mbggenerated Tue Feb 18 21:34:23 CST 2020
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column indb_product_tag.name
     *
     * @param name the value for indb_product_tag.name
     *
     * @mbggenerated Tue Feb 18 21:34:23 CST 2020
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column indb_product_tag.parent_id
     *
     * @return the value of indb_product_tag.parent_id
     *
     * @mbggenerated Tue Feb 18 21:34:23 CST 2020
     */
    public Integer getParentId() {
        return parentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column indb_product_tag.parent_id
     *
     * @param parentId the value for indb_product_tag.parent_id
     *
     * @mbggenerated Tue Feb 18 21:34:23 CST 2020
     */
    public void setParentId(Integer parentId) {
        this.parentId = parentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column indb_product_tag.sort
     *
     * @return the value of indb_product_tag.sort
     *
     * @mbggenerated Tue Feb 18 21:34:23 CST 2020
     */
    public Integer getSort() {
        return sort;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column indb_product_tag.sort
     *
     * @param sort the value for indb_product_tag.sort
     *
     * @mbggenerated Tue Feb 18 21:34:23 CST 2020
     */
    public void setSort(Integer sort) {
        this.sort = sort;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column indb_product_tag.is_deleted
     *
     * @return the value of indb_product_tag.is_deleted
     *
     * @mbggenerated Tue Feb 18 21:34:23 CST 2020
     */
    public Integer getIsDeleted() {
        return isDeleted;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column indb_product_tag.is_deleted
     *
     * @param isDeleted the value for indb_product_tag.is_deleted
     *
     * @mbggenerated Tue Feb 18 21:34:23 CST 2020
     */
    public void setIsDeleted(Integer isDeleted) {
        this.isDeleted = isDeleted;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column indb_product_tag.create_by
     *
     * @return the value of indb_product_tag.create_by
     *
     * @mbggenerated Tue Feb 18 21:34:23 CST 2020
     */
    public Integer getCreateBy() {
        return createBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column indb_product_tag.create_by
     *
     * @param createBy the value for indb_product_tag.create_by
     *
     * @mbggenerated Tue Feb 18 21:34:23 CST 2020
     */
    public void setCreateBy(Integer createBy) {
        this.createBy = createBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column indb_product_tag.create_name
     *
     * @return the value of indb_product_tag.create_name
     *
     * @mbggenerated Tue Feb 18 21:34:23 CST 2020
     */
    public String getCreateName() {
        return createName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column indb_product_tag.create_name
     *
     * @param createName the value for indb_product_tag.create_name
     *
     * @mbggenerated Tue Feb 18 21:34:23 CST 2020
     */
    public void setCreateName(String createName) {
        this.createName = createName == null ? null : createName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column indb_product_tag.create_time
     *
     * @return the value of indb_product_tag.create_time
     *
     * @mbggenerated Tue Feb 18 21:34:23 CST 2020
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column indb_product_tag.create_time
     *
     * @param createTime the value for indb_product_tag.create_time
     *
     * @mbggenerated Tue Feb 18 21:34:23 CST 2020
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column indb_product_tag.update_by
     *
     * @return the value of indb_product_tag.update_by
     *
     * @mbggenerated Tue Feb 18 21:34:23 CST 2020
     */
    public Integer getUpdateBy() {
        return updateBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column indb_product_tag.update_by
     *
     * @param updateBy the value for indb_product_tag.update_by
     *
     * @mbggenerated Tue Feb 18 21:34:23 CST 2020
     */
    public void setUpdateBy(Integer updateBy) {
        this.updateBy = updateBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column indb_product_tag.update_name
     *
     * @return the value of indb_product_tag.update_name
     *
     * @mbggenerated Tue Feb 18 21:34:23 CST 2020
     */
    public Date getUpdateName() {
        return updateName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column indb_product_tag.update_name
     *
     * @param updateName the value for indb_product_tag.update_name
     *
     * @mbggenerated Tue Feb 18 21:34:23 CST 2020
     */
    public void setUpdateName(Date updateName) {
        this.updateName = updateName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column indb_product_tag.update_time
     *
     * @return the value of indb_product_tag.update_time
     *
     * @mbggenerated Tue Feb 18 21:34:23 CST 2020
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column indb_product_tag.update_time
     *
     * @param updateTime the value for indb_product_tag.update_time
     *
     * @mbggenerated Tue Feb 18 21:34:23 CST 2020
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }
}