package com.industry.platform.dto.generator;

public class IndbBannerKey {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column indb_banner.id
     *
     * @mbggenerated Sun Dec 08 20:53:52 CST 2019
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column indb_banner.is_deleted
     *
     * @mbggenerated Sun Dec 08 20:53:52 CST 2019
     */
    private Integer isDeleted;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column indb_banner.id
     *
     * @return the value of indb_banner.id
     *
     * @mbggenerated Sun Dec 08 20:53:52 CST 2019
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column indb_banner.id
     *
     * @param id the value for indb_banner.id
     *
     * @mbggenerated Sun Dec 08 20:53:52 CST 2019
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column indb_banner.is_deleted
     *
     * @return the value of indb_banner.is_deleted
     *
     * @mbggenerated Sun Dec 08 20:53:52 CST 2019
     */
    public Integer getIsDeleted() {
        return isDeleted;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column indb_banner.is_deleted
     *
     * @param isDeleted the value for indb_banner.is_deleted
     *
     * @mbggenerated Sun Dec 08 20:53:52 CST 2019
     */
    public void setIsDeleted(Integer isDeleted) {
        this.isDeleted = isDeleted;
    }
}