package com.industry.platform.dto.generator;

import java.util.Date;

public class IndbBanner extends IndbBannerKey {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column indb_banner.name
     *
     * @mbggenerated Sun Dec 08 20:53:52 CST 2019
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column indb_banner.pic_path
     *
     * @mbggenerated Sun Dec 08 20:53:52 CST 2019
     */
    private String picPath;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column indb_banner.sort
     *
     * @mbggenerated Sun Dec 08 20:53:52 CST 2019
     */
    private Integer sort;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column indb_banner.create_user
     *
     * @mbggenerated Sun Dec 08 20:53:52 CST 2019
     */
    private Integer createUser;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column indb_banner.create_date
     *
     * @mbggenerated Sun Dec 08 20:53:52 CST 2019
     */
    private Date createDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column indb_banner.update_user
     *
     * @mbggenerated Sun Dec 08 20:53:52 CST 2019
     */
    private Integer updateUser;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column indb_banner.update_date
     *
     * @mbggenerated Sun Dec 08 20:53:52 CST 2019
     */
    private Date updateDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column indb_banner.content
     *
     * @mbggenerated Sun Dec 08 20:53:52 CST 2019
     */
    private String content;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column indb_banner.name
     *
     * @return the value of indb_banner.name
     *
     * @mbggenerated Sun Dec 08 20:53:52 CST 2019
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column indb_banner.name
     *
     * @param name the value for indb_banner.name
     *
     * @mbggenerated Sun Dec 08 20:53:52 CST 2019
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column indb_banner.pic_path
     *
     * @return the value of indb_banner.pic_path
     *
     * @mbggenerated Sun Dec 08 20:53:52 CST 2019
     */
    public String getPicPath() {
        return picPath;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column indb_banner.pic_path
     *
     * @param picPath the value for indb_banner.pic_path
     *
     * @mbggenerated Sun Dec 08 20:53:52 CST 2019
     */
    public void setPicPath(String picPath) {
        this.picPath = picPath == null ? null : picPath.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column indb_banner.sort
     *
     * @return the value of indb_banner.sort
     *
     * @mbggenerated Sun Dec 08 20:53:52 CST 2019
     */
    public Integer getSort() {
        return sort;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column indb_banner.sort
     *
     * @param sort the value for indb_banner.sort
     *
     * @mbggenerated Sun Dec 08 20:53:52 CST 2019
     */
    public void setSort(Integer sort) {
        this.sort = sort;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column indb_banner.create_user
     *
     * @return the value of indb_banner.create_user
     *
     * @mbggenerated Sun Dec 08 20:53:52 CST 2019
     */
    public Integer getCreateUser() {
        return createUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column indb_banner.create_user
     *
     * @param createUser the value for indb_banner.create_user
     *
     * @mbggenerated Sun Dec 08 20:53:52 CST 2019
     */
    public void setCreateUser(Integer createUser) {
        this.createUser = createUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column indb_banner.create_date
     *
     * @return the value of indb_banner.create_date
     *
     * @mbggenerated Sun Dec 08 20:53:52 CST 2019
     */
    public Date getCreateDate() {
        return createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column indb_banner.create_date
     *
     * @param createDate the value for indb_banner.create_date
     *
     * @mbggenerated Sun Dec 08 20:53:52 CST 2019
     */
    public void setCreateDate(Date createDate) {
        this.createDate = createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column indb_banner.update_user
     *
     * @return the value of indb_banner.update_user
     *
     * @mbggenerated Sun Dec 08 20:53:52 CST 2019
     */
    public Integer getUpdateUser() {
        return updateUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column indb_banner.update_user
     *
     * @param updateUser the value for indb_banner.update_user
     *
     * @mbggenerated Sun Dec 08 20:53:52 CST 2019
     */
    public void setUpdateUser(Integer updateUser) {
        this.updateUser = updateUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column indb_banner.update_date
     *
     * @return the value of indb_banner.update_date
     *
     * @mbggenerated Sun Dec 08 20:53:52 CST 2019
     */
    public Date getUpdateDate() {
        return updateDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column indb_banner.update_date
     *
     * @param updateDate the value for indb_banner.update_date
     *
     * @mbggenerated Sun Dec 08 20:53:52 CST 2019
     */
    public void setUpdateDate(Date updateDate) {
        this.updateDate = updateDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column indb_banner.content
     *
     * @return the value of indb_banner.content
     *
     * @mbggenerated Sun Dec 08 20:53:52 CST 2019
     */
    public String getContent() {
        return content;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column indb_banner.content
     *
     * @param content the value for indb_banner.content
     *
     * @mbggenerated Sun Dec 08 20:53:52 CST 2019
     */
    public void setContent(String content) {
        this.content = content == null ? null : content.trim();
    }
}