package com.industry.platform.dto.generator;

import java.util.Date;

public class IndbContract {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column indb_contract.id
     *
     * @mbggenerated Tue Feb 18 21:34:23 CST 2020
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column indb_contract.name
     *
     * @mbggenerated Tue Feb 18 21:34:23 CST 2020
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column indb_contract.email
     *
     * @mbggenerated Tue Feb 18 21:34:23 CST 2020
     */
    private String email;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column indb_contract.phone
     *
     * @mbggenerated Tue Feb 18 21:34:23 CST 2020
     */
    private String phone;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column indb_contract.is_reply
     *
     * @mbggenerated Tue Feb 18 21:34:23 CST 2020
     */
    private Integer isReply;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column indb_contract.create_by
     *
     * @mbggenerated Tue Feb 18 21:34:23 CST 2020
     */
    private String createBy;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column indb_contract.create_time
     *
     * @mbggenerated Tue Feb 18 21:34:23 CST 2020
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column indb_contract.update_by
     *
     * @mbggenerated Tue Feb 18 21:34:23 CST 2020
     */
    private String updateBy;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column indb_contract.update_time
     *
     * @mbggenerated Tue Feb 18 21:34:23 CST 2020
     */
    private Date updateTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column indb_contract.content
     *
     * @mbggenerated Tue Feb 18 21:34:23 CST 2020
     */
    private String content;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column indb_contract.id
     *
     * @return the value of indb_contract.id
     *
     * @mbggenerated Tue Feb 18 21:34:23 CST 2020
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column indb_contract.id
     *
     * @param id the value for indb_contract.id
     *
     * @mbggenerated Tue Feb 18 21:34:23 CST 2020
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column indb_contract.name
     *
     * @return the value of indb_contract.name
     *
     * @mbggenerated Tue Feb 18 21:34:23 CST 2020
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column indb_contract.name
     *
     * @param name the value for indb_contract.name
     *
     * @mbggenerated Tue Feb 18 21:34:23 CST 2020
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column indb_contract.email
     *
     * @return the value of indb_contract.email
     *
     * @mbggenerated Tue Feb 18 21:34:23 CST 2020
     */
    public String getEmail() {
        return email;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column indb_contract.email
     *
     * @param email the value for indb_contract.email
     *
     * @mbggenerated Tue Feb 18 21:34:23 CST 2020
     */
    public void setEmail(String email) {
        this.email = email == null ? null : email.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column indb_contract.phone
     *
     * @return the value of indb_contract.phone
     *
     * @mbggenerated Tue Feb 18 21:34:23 CST 2020
     */
    public String getPhone() {
        return phone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column indb_contract.phone
     *
     * @param phone the value for indb_contract.phone
     *
     * @mbggenerated Tue Feb 18 21:34:23 CST 2020
     */
    public void setPhone(String phone) {
        this.phone = phone == null ? null : phone.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column indb_contract.is_reply
     *
     * @return the value of indb_contract.is_reply
     *
     * @mbggenerated Tue Feb 18 21:34:23 CST 2020
     */
    public Integer getIsReply() {
        return isReply;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column indb_contract.is_reply
     *
     * @param isReply the value for indb_contract.is_reply
     *
     * @mbggenerated Tue Feb 18 21:34:23 CST 2020
     */
    public void setIsReply(Integer isReply) {
        this.isReply = isReply;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column indb_contract.create_by
     *
     * @return the value of indb_contract.create_by
     *
     * @mbggenerated Tue Feb 18 21:34:23 CST 2020
     */
    public String getCreateBy() {
        return createBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column indb_contract.create_by
     *
     * @param createBy the value for indb_contract.create_by
     *
     * @mbggenerated Tue Feb 18 21:34:23 CST 2020
     */
    public void setCreateBy(String createBy) {
        this.createBy = createBy == null ? null : createBy.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column indb_contract.create_time
     *
     * @return the value of indb_contract.create_time
     *
     * @mbggenerated Tue Feb 18 21:34:23 CST 2020
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column indb_contract.create_time
     *
     * @param createTime the value for indb_contract.create_time
     *
     * @mbggenerated Tue Feb 18 21:34:23 CST 2020
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column indb_contract.update_by
     *
     * @return the value of indb_contract.update_by
     *
     * @mbggenerated Tue Feb 18 21:34:23 CST 2020
     */
    public String getUpdateBy() {
        return updateBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column indb_contract.update_by
     *
     * @param updateBy the value for indb_contract.update_by
     *
     * @mbggenerated Tue Feb 18 21:34:23 CST 2020
     */
    public void setUpdateBy(String updateBy) {
        this.updateBy = updateBy == null ? null : updateBy.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column indb_contract.update_time
     *
     * @return the value of indb_contract.update_time
     *
     * @mbggenerated Tue Feb 18 21:34:23 CST 2020
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column indb_contract.update_time
     *
     * @param updateTime the value for indb_contract.update_time
     *
     * @mbggenerated Tue Feb 18 21:34:23 CST 2020
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column indb_contract.content
     *
     * @return the value of indb_contract.content
     *
     * @mbggenerated Tue Feb 18 21:34:23 CST 2020
     */
    public String getContent() {
        return content;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column indb_contract.content
     *
     * @param content the value for indb_contract.content
     *
     * @mbggenerated Tue Feb 18 21:34:23 CST 2020
     */
    public void setContent(String content) {
        this.content = content == null ? null : content.trim();
    }
}