package com.industry.platform.dto.generator;

public class IndbNewsKey {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column indb_news.id
     *
     * @mbggenerated Tue Feb 11 13:03:47 CST 2020
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column indb_news.is_used
     *
     * @mbggenerated Tue Feb 11 13:03:47 CST 2020
     */
    private Integer isUsed;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column indb_news.id
     *
     * @return the value of indb_news.id
     *
     * @mbggenerated Tue Feb 11 13:03:47 CST 2020
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column indb_news.id
     *
     * @param id the value for indb_news.id
     *
     * @mbggenerated Tue Feb 11 13:03:47 CST 2020
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column indb_news.is_used
     *
     * @return the value of indb_news.is_used
     *
     * @mbggenerated Tue Feb 11 13:03:47 CST 2020
     */
    public Integer getIsUsed() {
        return isUsed;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column indb_news.is_used
     *
     * @param isUsed the value for indb_news.is_used
     *
     * @mbggenerated Tue Feb 11 13:03:47 CST 2020
     */
    public void setIsUsed(Integer isUsed) {
        this.isUsed = isUsed;
    }
}