package com.industry.platform.dto.generator;

import java.util.Date;

public class IndbBanner extends IndbBannerKey {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column indb_banner.name
     *
     * @mbggenerated Tue Feb 18 21:34:23 CST 2020
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column indb_banner.pic_path
     *
     * @mbggenerated Tue Feb 18 21:34:23 CST 2020
     */
    private String picPath;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column indb_banner.sort
     *
     * @mbggenerated Tue Feb 18 21:34:23 CST 2020
     */
    private Integer sort;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column indb_banner.create_by
     *
     * @mbggenerated Tue Feb 18 21:34:23 CST 2020
     */
    private String createBy;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column indb_banner.create_time
     *
     * @mbggenerated Tue Feb 18 21:34:23 CST 2020
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column indb_banner.update_by
     *
     * @mbggenerated Tue Feb 18 21:34:23 CST 2020
     */
    private String updateBy;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column indb_banner.update_time
     *
     * @mbggenerated Tue Feb 18 21:34:23 CST 2020
     */
    private Date updateTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column indb_banner.content
     *
     * @mbggenerated Tue Feb 18 21:34:23 CST 2020
     */
    private String content;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column indb_banner.name
     *
     * @return the value of indb_banner.name
     *
     * @mbggenerated Tue Feb 18 21:34:23 CST 2020
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column indb_banner.name
     *
     * @param name the value for indb_banner.name
     *
     * @mbggenerated Tue Feb 18 21:34:23 CST 2020
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column indb_banner.pic_path
     *
     * @return the value of indb_banner.pic_path
     *
     * @mbggenerated Tue Feb 18 21:34:23 CST 2020
     */
    public String getPicPath() {
        return picPath;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column indb_banner.pic_path
     *
     * @param picPath the value for indb_banner.pic_path
     *
     * @mbggenerated Tue Feb 18 21:34:23 CST 2020
     */
    public void setPicPath(String picPath) {
        this.picPath = picPath == null ? null : picPath.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column indb_banner.sort
     *
     * @return the value of indb_banner.sort
     *
     * @mbggenerated Tue Feb 18 21:34:23 CST 2020
     */
    public Integer getSort() {
        return sort;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column indb_banner.sort
     *
     * @param sort the value for indb_banner.sort
     *
     * @mbggenerated Tue Feb 18 21:34:23 CST 2020
     */
    public void setSort(Integer sort) {
        this.sort = sort;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column indb_banner.create_by
     *
     * @return the value of indb_banner.create_by
     *
     * @mbggenerated Tue Feb 18 21:34:23 CST 2020
     */
    public String getCreateBy() {
        return createBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column indb_banner.create_by
     *
     * @param createBy the value for indb_banner.create_by
     *
     * @mbggenerated Tue Feb 18 21:34:23 CST 2020
     */
    public void setCreateBy(String createBy) {
        this.createBy = createBy == null ? null : createBy.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column indb_banner.create_time
     *
     * @return the value of indb_banner.create_time
     *
     * @mbggenerated Tue Feb 18 21:34:23 CST 2020
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column indb_banner.create_time
     *
     * @param createTime the value for indb_banner.create_time
     *
     * @mbggenerated Tue Feb 18 21:34:23 CST 2020
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column indb_banner.update_by
     *
     * @return the value of indb_banner.update_by
     *
     * @mbggenerated Tue Feb 18 21:34:23 CST 2020
     */
    public String getUpdateBy() {
        return updateBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column indb_banner.update_by
     *
     * @param updateBy the value for indb_banner.update_by
     *
     * @mbggenerated Tue Feb 18 21:34:23 CST 2020
     */
    public void setUpdateBy(String updateBy) {
        this.updateBy = updateBy == null ? null : updateBy.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column indb_banner.update_time
     *
     * @return the value of indb_banner.update_time
     *
     * @mbggenerated Tue Feb 18 21:34:23 CST 2020
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column indb_banner.update_time
     *
     * @param updateTime the value for indb_banner.update_time
     *
     * @mbggenerated Tue Feb 18 21:34:23 CST 2020
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column indb_banner.content
     *
     * @return the value of indb_banner.content
     *
     * @mbggenerated Tue Feb 18 21:34:23 CST 2020
     */
    public String getContent() {
        return content;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column indb_banner.content
     *
     * @param content the value for indb_banner.content
     *
     * @mbggenerated Tue Feb 18 21:34:23 CST 2020
     */
    public void setContent(String content) {
        this.content = content == null ? null : content.trim();
    }
}