package com.industry.platform.dto.generator;

import java.util.Date;

public class IndbUserInfo {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column indb_user_info.id
     *
     * @mbggenerated Tue Feb 18 21:34:23 CST 2020
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column indb_user_info.name
     *
     * @mbggenerated Tue Feb 18 21:34:23 CST 2020
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column indb_user_info.phone
     *
     * @mbggenerated Tue Feb 18 21:34:23 CST 2020
     */
    private String phone;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column indb_user_info.password
     *
     * @mbggenerated Tue Feb 18 21:34:23 CST 2020
     */
    private String password;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column indb_user_info.gende
     *
     * @mbggenerated Tue Feb 18 21:34:23 CST 2020
     */
    private Byte gende;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column indb_user_info.wechat
     *
     * @mbggenerated Tue Feb 18 21:34:23 CST 2020
     */
    private String wechat;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column indb_user_info.whatsapp
     *
     * @mbggenerated Tue Feb 18 21:34:23 CST 2020
     */
    private String whatsapp;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column indb_user_info.qq
     *
     * @mbggenerated Tue Feb 18 21:34:23 CST 2020
     */
    private String qq;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column indb_user_info.create_time
     *
     * @mbggenerated Tue Feb 18 21:34:23 CST 2020
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column indb_user_info.update_time
     *
     * @mbggenerated Tue Feb 18 21:34:23 CST 2020
     */
    private Date updateTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column indb_user_info.is_delate
     *
     * @mbggenerated Tue Feb 18 21:34:23 CST 2020
     */
    private Boolean isDelate;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column indb_user_info.id
     *
     * @return the value of indb_user_info.id
     *
     * @mbggenerated Tue Feb 18 21:34:23 CST 2020
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column indb_user_info.id
     *
     * @param id the value for indb_user_info.id
     *
     * @mbggenerated Tue Feb 18 21:34:23 CST 2020
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column indb_user_info.name
     *
     * @return the value of indb_user_info.name
     *
     * @mbggenerated Tue Feb 18 21:34:23 CST 2020
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column indb_user_info.name
     *
     * @param name the value for indb_user_info.name
     *
     * @mbggenerated Tue Feb 18 21:34:23 CST 2020
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column indb_user_info.phone
     *
     * @return the value of indb_user_info.phone
     *
     * @mbggenerated Tue Feb 18 21:34:23 CST 2020
     */
    public String getPhone() {
        return phone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column indb_user_info.phone
     *
     * @param phone the value for indb_user_info.phone
     *
     * @mbggenerated Tue Feb 18 21:34:23 CST 2020
     */
    public void setPhone(String phone) {
        this.phone = phone == null ? null : phone.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column indb_user_info.password
     *
     * @return the value of indb_user_info.password
     *
     * @mbggenerated Tue Feb 18 21:34:23 CST 2020
     */
    public String getPassword() {
        return password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column indb_user_info.password
     *
     * @param password the value for indb_user_info.password
     *
     * @mbggenerated Tue Feb 18 21:34:23 CST 2020
     */
    public void setPassword(String password) {
        this.password = password == null ? null : password.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column indb_user_info.gende
     *
     * @return the value of indb_user_info.gende
     *
     * @mbggenerated Tue Feb 18 21:34:23 CST 2020
     */
    public Byte getGende() {
        return gende;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column indb_user_info.gende
     *
     * @param gende the value for indb_user_info.gende
     *
     * @mbggenerated Tue Feb 18 21:34:23 CST 2020
     */
    public void setGende(Byte gende) {
        this.gende = gende;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column indb_user_info.wechat
     *
     * @return the value of indb_user_info.wechat
     *
     * @mbggenerated Tue Feb 18 21:34:23 CST 2020
     */
    public String getWechat() {
        return wechat;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column indb_user_info.wechat
     *
     * @param wechat the value for indb_user_info.wechat
     *
     * @mbggenerated Tue Feb 18 21:34:23 CST 2020
     */
    public void setWechat(String wechat) {
        this.wechat = wechat == null ? null : wechat.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column indb_user_info.whatsapp
     *
     * @return the value of indb_user_info.whatsapp
     *
     * @mbggenerated Tue Feb 18 21:34:23 CST 2020
     */
    public String getWhatsapp() {
        return whatsapp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column indb_user_info.whatsapp
     *
     * @param whatsapp the value for indb_user_info.whatsapp
     *
     * @mbggenerated Tue Feb 18 21:34:23 CST 2020
     */
    public void setWhatsapp(String whatsapp) {
        this.whatsapp = whatsapp == null ? null : whatsapp.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column indb_user_info.qq
     *
     * @return the value of indb_user_info.qq
     *
     * @mbggenerated Tue Feb 18 21:34:23 CST 2020
     */
    public String getQq() {
        return qq;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column indb_user_info.qq
     *
     * @param qq the value for indb_user_info.qq
     *
     * @mbggenerated Tue Feb 18 21:34:23 CST 2020
     */
    public void setQq(String qq) {
        this.qq = qq == null ? null : qq.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column indb_user_info.create_time
     *
     * @return the value of indb_user_info.create_time
     *
     * @mbggenerated Tue Feb 18 21:34:23 CST 2020
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column indb_user_info.create_time
     *
     * @param createTime the value for indb_user_info.create_time
     *
     * @mbggenerated Tue Feb 18 21:34:23 CST 2020
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column indb_user_info.update_time
     *
     * @return the value of indb_user_info.update_time
     *
     * @mbggenerated Tue Feb 18 21:34:23 CST 2020
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column indb_user_info.update_time
     *
     * @param updateTime the value for indb_user_info.update_time
     *
     * @mbggenerated Tue Feb 18 21:34:23 CST 2020
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column indb_user_info.is_delate
     *
     * @return the value of indb_user_info.is_delate
     *
     * @mbggenerated Tue Feb 18 21:34:23 CST 2020
     */
    public Boolean getIsDelate() {
        return isDelate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column indb_user_info.is_delate
     *
     * @param isDelate the value for indb_user_info.is_delate
     *
     * @mbggenerated Tue Feb 18 21:34:23 CST 2020
     */
    public void setIsDelate(Boolean isDelate) {
        this.isDelate = isDelate;
    }
}