package com.industry.platform.dao.generator;

import com.industry.platform.dto.generator.IndbProductTag;
import com.industry.platform.dto.generator.IndbProductTagExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface IndbProductTagMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table indb_product_tag
     *
     * @mbggenerated Sun Dec 08 20:53:52 CST 2019
     */
    int countByExample(IndbProductTagExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table indb_product_tag
     *
     * @mbggenerated Sun Dec 08 20:53:52 CST 2019
     */
    int deleteByExample(IndbProductTagExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table indb_product_tag
     *
     * @mbggenerated Sun Dec 08 20:53:52 CST 2019
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table indb_product_tag
     *
     * @mbggenerated Sun Dec 08 20:53:52 CST 2019
     */
    int insert(IndbProductTag record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table indb_product_tag
     *
     * @mbggenerated Sun Dec 08 20:53:52 CST 2019
     */
    int insertSelective(IndbProductTag record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table indb_product_tag
     *
     * @mbggenerated Sun Dec 08 20:53:52 CST 2019
     */
    List<IndbProductTag> selectByExample(IndbProductTagExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table indb_product_tag
     *
     * @mbggenerated Sun Dec 08 20:53:52 CST 2019
     */
    IndbProductTag selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table indb_product_tag
     *
     * @mbggenerated Sun Dec 08 20:53:52 CST 2019
     */
    int updateByExampleSelective(@Param("record") IndbProductTag record, @Param("example") IndbProductTagExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table indb_product_tag
     *
     * @mbggenerated Sun Dec 08 20:53:52 CST 2019
     */
    int updateByExample(@Param("record") IndbProductTag record, @Param("example") IndbProductTagExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table indb_product_tag
     *
     * @mbggenerated Sun Dec 08 20:53:52 CST 2019
     */
    int updateByPrimaryKeySelective(IndbProductTag record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table indb_product_tag
     *
     * @mbggenerated Sun Dec 08 20:53:52 CST 2019
     */
    int updateByPrimaryKey(IndbProductTag record);
}