package com.industry.platform.dao.generator;

import com.industry.platform.dto.generator.IndbAttachment;
import com.industry.platform.dto.generator.IndbAttachmentExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface IndbAttachmentMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table indb_attachment
     *
     * @mbggenerated Tue Feb 18 21:34:23 CST 2020
     */
    int countByExample(IndbAttachmentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table indb_attachment
     *
     * @mbggenerated Tue Feb 18 21:34:23 CST 2020
     */
    int deleteByExample(IndbAttachmentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table indb_attachment
     *
     * @mbggenerated Tue Feb 18 21:34:23 CST 2020
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table indb_attachment
     *
     * @mbggenerated Tue Feb 18 21:34:23 CST 2020
     */
    int insert(IndbAttachment record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table indb_attachment
     *
     * @mbggenerated Tue Feb 18 21:34:23 CST 2020
     */
    int insertSelective(IndbAttachment record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table indb_attachment
     *
     * @mbggenerated Tue Feb 18 21:34:23 CST 2020
     */
    List<IndbAttachment> selectByExample(IndbAttachmentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table indb_attachment
     *
     * @mbggenerated Tue Feb 18 21:34:23 CST 2020
     */
    IndbAttachment selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table indb_attachment
     *
     * @mbggenerated Tue Feb 18 21:34:23 CST 2020
     */
    int updateByExampleSelective(@Param("record") IndbAttachment record, @Param("example") IndbAttachmentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table indb_attachment
     *
     * @mbggenerated Tue Feb 18 21:34:23 CST 2020
     */
    int updateByExample(@Param("record") IndbAttachment record, @Param("example") IndbAttachmentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table indb_attachment
     *
     * @mbggenerated Tue Feb 18 21:34:23 CST 2020
     */
    int updateByPrimaryKeySelective(IndbAttachment record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table indb_attachment
     *
     * @mbggenerated Tue Feb 18 21:34:23 CST 2020
     */
    int updateByPrimaryKey(IndbAttachment record);
}