package com.industry.platform.dao.generator;

import com.industry.platform.dto.generator.IndbProductDetail;
import com.industry.platform.dto.generator.IndbProductDetailExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface IndbProductDetailMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table indb_product_detail
     *
     * @mbggenerated Sun Dec 08 20:53:52 CST 2019
     */
    int countByExample(IndbProductDetailExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table indb_product_detail
     *
     * @mbggenerated Sun Dec 08 20:53:52 CST 2019
     */
    int deleteByExample(IndbProductDetailExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table indb_product_detail
     *
     * @mbggenerated Sun Dec 08 20:53:52 CST 2019
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table indb_product_detail
     *
     * @mbggenerated Sun Dec 08 20:53:52 CST 2019
     */
    int insert(IndbProductDetail record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table indb_product_detail
     *
     * @mbggenerated Sun Dec 08 20:53:52 CST 2019
     */
    int insertSelective(IndbProductDetail record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table indb_product_detail
     *
     * @mbggenerated Sun Dec 08 20:53:52 CST 2019
     */
    List<IndbProductDetail> selectByExample(IndbProductDetailExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table indb_product_detail
     *
     * @mbggenerated Sun Dec 08 20:53:52 CST 2019
     */
    IndbProductDetail selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table indb_product_detail
     *
     * @mbggenerated Sun Dec 08 20:53:52 CST 2019
     */
    int updateByExampleSelective(@Param("record") IndbProductDetail record, @Param("example") IndbProductDetailExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table indb_product_detail
     *
     * @mbggenerated Sun Dec 08 20:53:52 CST 2019
     */
    int updateByExample(@Param("record") IndbProductDetail record, @Param("example") IndbProductDetailExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table indb_product_detail
     *
     * @mbggenerated Sun Dec 08 20:53:52 CST 2019
     */
    int updateByPrimaryKeySelective(IndbProductDetail record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table indb_product_detail
     *
     * @mbggenerated Sun Dec 08 20:53:52 CST 2019
     */
    int updateByPrimaryKey(IndbProductDetail record);
}