package com.industry.platform.dao.generator;

import com.industry.platform.dto.generator.IndbNews;
import com.industry.platform.dto.generator.IndbNewsExample;
import com.industry.platform.dto.generator.IndbNewsKey;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface IndbNewsMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table indb_news
     *
     * @mbggenerated Tue Feb 11 13:03:47 CST 2020
     */
    int countByExample(IndbNewsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table indb_news
     *
     * @mbggenerated Tue Feb 11 13:03:47 CST 2020
     */
    int deleteByExample(IndbNewsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table indb_news
     *
     * @mbggenerated Tue Feb 11 13:03:47 CST 2020
     */
    int deleteByPrimaryKey(IndbNewsKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table indb_news
     *
     * @mbggenerated Tue Feb 11 13:03:47 CST 2020
     */
    int insert(IndbNews record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table indb_news
     *
     * @mbggenerated Tue Feb 11 13:03:47 CST 2020
     */
    int insertSelective(IndbNews record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table indb_news
     *
     * @mbggenerated Tue Feb 11 13:03:47 CST 2020
     */
    List<IndbNews> selectByExampleWithBLOBs(IndbNewsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table indb_news
     *
     * @mbggenerated Tue Feb 11 13:03:47 CST 2020
     */
    List<IndbNews> selectByExample(IndbNewsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table indb_news
     *
     * @mbggenerated Tue Feb 11 13:03:47 CST 2020
     */
    IndbNews selectByPrimaryKey(IndbNewsKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table indb_news
     *
     * @mbggenerated Tue Feb 11 13:03:47 CST 2020
     */
    int updateByExampleSelective(@Param("record") IndbNews record, @Param("example") IndbNewsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table indb_news
     *
     * @mbggenerated Tue Feb 11 13:03:47 CST 2020
     */
    int updateByExampleWithBLOBs(@Param("record") IndbNews record, @Param("example") IndbNewsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table indb_news
     *
     * @mbggenerated Tue Feb 11 13:03:47 CST 2020
     */
    int updateByExample(@Param("record") IndbNews record, @Param("example") IndbNewsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table indb_news
     *
     * @mbggenerated Tue Feb 11 13:03:47 CST 2020
     */
    int updateByPrimaryKeySelective(IndbNews record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table indb_news
     *
     * @mbggenerated Tue Feb 11 13:03:47 CST 2020
     */
    int updateByPrimaryKeyWithBLOBs(IndbNews record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table indb_news
     *
     * @mbggenerated Tue Feb 11 13:03:47 CST 2020
     */
    int updateByPrimaryKey(IndbNews record);
}