package com.industry.platform.dao.generator;

import com.industry.platform.dto.generator.IndbBanner;
import com.industry.platform.dto.generator.IndbBannerExample;
import com.industry.platform.dto.generator.IndbBannerKey;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface IndbBannerMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table indb_banner
     *
     * @mbggenerated Tue Feb 18 21:34:23 CST 2020
     */
    int countByExample(IndbBannerExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table indb_banner
     *
     * @mbggenerated Tue Feb 18 21:34:23 CST 2020
     */
    int deleteByExample(IndbBannerExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table indb_banner
     *
     * @mbggenerated Tue Feb 18 21:34:23 CST 2020
     */
    int deleteByPrimaryKey(IndbBannerKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table indb_banner
     *
     * @mbggenerated Tue Feb 18 21:34:23 CST 2020
     */
    int insert(IndbBanner record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table indb_banner
     *
     * @mbggenerated Tue Feb 18 21:34:23 CST 2020
     */
    int insertSelective(IndbBanner record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table indb_banner
     *
     * @mbggenerated Tue Feb 18 21:34:23 CST 2020
     */
    List<IndbBanner> selectByExampleWithBLOBs(IndbBannerExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table indb_banner
     *
     * @mbggenerated Tue Feb 18 21:34:23 CST 2020
     */
    List<IndbBanner> selectByExample(IndbBannerExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table indb_banner
     *
     * @mbggenerated Tue Feb 18 21:34:23 CST 2020
     */
    IndbBanner selectByPrimaryKey(IndbBannerKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table indb_banner
     *
     * @mbggenerated Tue Feb 18 21:34:23 CST 2020
     */
    int updateByExampleSelective(@Param("record") IndbBanner record, @Param("example") IndbBannerExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table indb_banner
     *
     * @mbggenerated Tue Feb 18 21:34:23 CST 2020
     */
    int updateByExampleWithBLOBs(@Param("record") IndbBanner record, @Param("example") IndbBannerExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table indb_banner
     *
     * @mbggenerated Tue Feb 18 21:34:23 CST 2020
     */
    int updateByExample(@Param("record") IndbBanner record, @Param("example") IndbBannerExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table indb_banner
     *
     * @mbggenerated Tue Feb 18 21:34:23 CST 2020
     */
    int updateByPrimaryKeySelective(IndbBanner record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table indb_banner
     *
     * @mbggenerated Tue Feb 18 21:34:23 CST 2020
     */
    int updateByPrimaryKeyWithBLOBs(IndbBanner record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table indb_banner
     *
     * @mbggenerated Tue Feb 18 21:34:23 CST 2020
     */
    int updateByPrimaryKey(IndbBanner record);
}