package com.industry.platform.dao.generator;

import com.industry.platform.dto.generator.IndbArticle;
import com.industry.platform.dto.generator.IndbArticleExample;
import com.industry.platform.dto.generator.IndbArticleKey;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface IndbArticleMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table indb_article
     *
     * @mbggenerated Tue Feb 18 21:34:23 CST 2020
     */
    int countByExample(IndbArticleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table indb_article
     *
     * @mbggenerated Tue Feb 18 21:34:23 CST 2020
     */
    int deleteByExample(IndbArticleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table indb_article
     *
     * @mbggenerated Tue Feb 18 21:34:23 CST 2020
     */
    int deleteByPrimaryKey(IndbArticleKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table indb_article
     *
     * @mbggenerated Tue Feb 18 21:34:23 CST 2020
     */
    int insert(IndbArticle record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table indb_article
     *
     * @mbggenerated Tue Feb 18 21:34:23 CST 2020
     */
    int insertSelective(IndbArticle record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table indb_article
     *
     * @mbggenerated Tue Feb 18 21:34:23 CST 2020
     */
    List<IndbArticle> selectByExampleWithBLOBs(IndbArticleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table indb_article
     *
     * @mbggenerated Tue Feb 18 21:34:23 CST 2020
     */
    List<IndbArticle> selectByExample(IndbArticleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table indb_article
     *
     * @mbggenerated Tue Feb 18 21:34:23 CST 2020
     */
    IndbArticle selectByPrimaryKey(IndbArticleKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table indb_article
     *
     * @mbggenerated Tue Feb 18 21:34:23 CST 2020
     */
    int updateByExampleSelective(@Param("record") IndbArticle record, @Param("example") IndbArticleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table indb_article
     *
     * @mbggenerated Tue Feb 18 21:34:23 CST 2020
     */
    int updateByExampleWithBLOBs(@Param("record") IndbArticle record, @Param("example") IndbArticleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table indb_article
     *
     * @mbggenerated Tue Feb 18 21:34:23 CST 2020
     */
    int updateByExample(@Param("record") IndbArticle record, @Param("example") IndbArticleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table indb_article
     *
     * @mbggenerated Tue Feb 18 21:34:23 CST 2020
     */
    int updateByPrimaryKeySelective(IndbArticle record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table indb_article
     *
     * @mbggenerated Tue Feb 18 21:34:23 CST 2020
     */
    int updateByPrimaryKeyWithBLOBs(IndbArticle record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table indb_article
     *
     * @mbggenerated Tue Feb 18 21:34:23 CST 2020
     */
    int updateByPrimaryKey(IndbArticle record);
}