package com.industry.platform.dao.generator;

import com.industry.platform.dto.generator.IndbProperty;
import com.industry.platform.dto.generator.IndbPropertyExample;
import com.industry.platform.dto.generator.IndbPropertyKey;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface IndbPropertyMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table indb_property
     *
     * @mbggenerated Sun Dec 08 20:53:52 CST 2019
     */
    int countByExample(IndbPropertyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table indb_property
     *
     * @mbggenerated Sun Dec 08 20:53:52 CST 2019
     */
    int deleteByExample(IndbPropertyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table indb_property
     *
     * @mbggenerated Sun Dec 08 20:53:52 CST 2019
     */
    int deleteByPrimaryKey(IndbPropertyKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table indb_property
     *
     * @mbggenerated Sun Dec 08 20:53:52 CST 2019
     */
    int insert(IndbProperty record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table indb_property
     *
     * @mbggenerated Sun Dec 08 20:53:52 CST 2019
     */
    int insertSelective(IndbProperty record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table indb_property
     *
     * @mbggenerated Sun Dec 08 20:53:52 CST 2019
     */
    List<IndbProperty> selectByExampleWithBLOBs(IndbPropertyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table indb_property
     *
     * @mbggenerated Sun Dec 08 20:53:52 CST 2019
     */
    List<IndbProperty> selectByExample(IndbPropertyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table indb_property
     *
     * @mbggenerated Sun Dec 08 20:53:52 CST 2019
     */
    IndbProperty selectByPrimaryKey(IndbPropertyKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table indb_property
     *
     * @mbggenerated Sun Dec 08 20:53:52 CST 2019
     */
    int updateByExampleSelective(@Param("record") IndbProperty record, @Param("example") IndbPropertyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table indb_property
     *
     * @mbggenerated Sun Dec 08 20:53:52 CST 2019
     */
    int updateByExampleWithBLOBs(@Param("record") IndbProperty record, @Param("example") IndbPropertyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table indb_property
     *
     * @mbggenerated Sun Dec 08 20:53:52 CST 2019
     */
    int updateByExample(@Param("record") IndbProperty record, @Param("example") IndbPropertyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table indb_property
     *
     * @mbggenerated Sun Dec 08 20:53:52 CST 2019
     */
    int updateByPrimaryKeySelective(IndbProperty record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table indb_property
     *
     * @mbggenerated Sun Dec 08 20:53:52 CST 2019
     */
    int updateByPrimaryKeyWithBLOBs(IndbProperty record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table indb_property
     *
     * @mbggenerated Sun Dec 08 20:53:52 CST 2019
     */
    int updateByPrimaryKey(IndbProperty record);
}