package com.industry.platform.dao.generator;

import com.industry.platform.dto.generator.IndbUserInfo;
import com.industry.platform.dto.generator.IndbUserInfoExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface IndbUserInfoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table indb_user_info
     *
     * @mbggenerated Tue Feb 18 21:34:23 CST 2020
     */
    int countByExample(IndbUserInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table indb_user_info
     *
     * @mbggenerated Tue Feb 18 21:34:23 CST 2020
     */
    int deleteByExample(IndbUserInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table indb_user_info
     *
     * @mbggenerated Tue Feb 18 21:34:23 CST 2020
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table indb_user_info
     *
     * @mbggenerated Tue Feb 18 21:34:23 CST 2020
     */
    int insert(IndbUserInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table indb_user_info
     *
     * @mbggenerated Tue Feb 18 21:34:23 CST 2020
     */
    int insertSelective(IndbUserInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table indb_user_info
     *
     * @mbggenerated Tue Feb 18 21:34:23 CST 2020
     */
    List<IndbUserInfo> selectByExample(IndbUserInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table indb_user_info
     *
     * @mbggenerated Tue Feb 18 21:34:23 CST 2020
     */
    IndbUserInfo selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table indb_user_info
     *
     * @mbggenerated Tue Feb 18 21:34:23 CST 2020
     */
    int updateByExampleSelective(@Param("record") IndbUserInfo record, @Param("example") IndbUserInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table indb_user_info
     *
     * @mbggenerated Tue Feb 18 21:34:23 CST 2020
     */
    int updateByExample(@Param("record") IndbUserInfo record, @Param("example") IndbUserInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table indb_user_info
     *
     * @mbggenerated Tue Feb 18 21:34:23 CST 2020
     */
    int updateByPrimaryKeySelective(IndbUserInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table indb_user_info
     *
     * @mbggenerated Tue Feb 18 21:34:23 CST 2020
     */
    int updateByPrimaryKey(IndbUserInfo record);
}