package com.industry.platform.dao.generator;

import com.industry.platform.dto.generator.IndbContract;
import com.industry.platform.dto.generator.IndbContractExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface IndbContractMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table indb_contract
     *
     * @mbggenerated Sun Dec 08 20:53:52 CST 2019
     */
    int countByExample(IndbContractExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table indb_contract
     *
     * @mbggenerated Sun Dec 08 20:53:52 CST 2019
     */
    int deleteByExample(IndbContractExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table indb_contract
     *
     * @mbggenerated Sun Dec 08 20:53:52 CST 2019
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table indb_contract
     *
     * @mbggenerated Sun Dec 08 20:53:52 CST 2019
     */
    int insert(IndbContract record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table indb_contract
     *
     * @mbggenerated Sun Dec 08 20:53:52 CST 2019
     */
    int insertSelective(IndbContract record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table indb_contract
     *
     * @mbggenerated Sun Dec 08 20:53:52 CST 2019
     */
    List<IndbContract> selectByExampleWithBLOBs(IndbContractExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table indb_contract
     *
     * @mbggenerated Sun Dec 08 20:53:52 CST 2019
     */
    List<IndbContract> selectByExample(IndbContractExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table indb_contract
     *
     * @mbggenerated Sun Dec 08 20:53:52 CST 2019
     */
    IndbContract selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table indb_contract
     *
     * @mbggenerated Sun Dec 08 20:53:52 CST 2019
     */
    int updateByExampleSelective(@Param("record") IndbContract record, @Param("example") IndbContractExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table indb_contract
     *
     * @mbggenerated Sun Dec 08 20:53:52 CST 2019
     */
    int updateByExampleWithBLOBs(@Param("record") IndbContract record, @Param("example") IndbContractExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table indb_contract
     *
     * @mbggenerated Sun Dec 08 20:53:52 CST 2019
     */
    int updateByExample(@Param("record") IndbContract record, @Param("example") IndbContractExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table indb_contract
     *
     * @mbggenerated Sun Dec 08 20:53:52 CST 2019
     */
    int updateByPrimaryKeySelective(IndbContract record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table indb_contract
     *
     * @mbggenerated Sun Dec 08 20:53:52 CST 2019
     */
    int updateByPrimaryKeyWithBLOBs(IndbContract record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table indb_contract
     *
     * @mbggenerated Sun Dec 08 20:53:52 CST 2019
     */
    int updateByPrimaryKey(IndbContract record);
}